src/__tests__/jsonPointerToPath.ts, src/__tests__/pathToJsonPointer.spec.ts, src/_utils.ts, src/index.ts, src/pathToPointer.ts, src/pointerToPath.ts
These are extracted and cleaned up from the json-ref-parser repo. The are generically applicable to everywhere we want to work with json pointers (graph, ui-tree, studio, etc).
@P0lip and @rainum - if one of you takes the ui-tree task (SL-275), these helpers might help to work with those paths.
=> feat: add pointer helpers

src/__tests__/toPropertyPath.spec.ts, src/toPropertyPath.ts
This PR fixes `toPropertyPath` function for case when there are dots in path:
`/path/to/some/.dots/`
Before: `path.to.some..dots` <- bad :(
After: `path.to.some.[".dots"]` <- good :)
=> fix: handling dots-in-path case

src/__tests__/safeStringify.ts, src/index.ts, src/isStringified.ts, src/safeStringify.ts
I'm not sure if that's a design or an oversight, but our implementation of `safeStringify` is not compliant with `JSON.stringify`.
Today, when working on Studio, I noticed nulls are not stringified correctly.
This lead to a subtle errors where for instance `[null, 'foo].join('')` results in `'foo'` rather than `'nullfoo'`.
Since all falsy values are not stringified, `zero`, `false` etc. are not stringified at all as well, which, I don't think is intended.
The other issue I noticed is that we don't stringify strings - this, IMHO, is another issue.
I'd expect every string to be stringified again so that I can parse it with `JSON.parse` later on.
The former behavior is definitely an issue. I suppose we wanted to filter out `undefined` values, but by an accident, we also ignore other falsy …
=> fix: safeStringify should follow JSON.stringify

src/__tests__/fixtures/todos.oas2.json, src/__tests__/getLocationForJsonPath.spec.ts, src/getJsonPathForPosition.ts, src/getLocationForJsonPath.ts, src/safeParse.ts, yarn.lock
There was a minor inconsistency between JSON variant of `getLocationForJsonPath` and the YAML one.
In the case of YAML, the lookup is more relaxed and does not bail out entirely if a node at a given path does not exist.
It always returns the closest node while the JSON equivalent returns undefined.
This lead to a few subtle issues with Spectral relaxed returns the closest parent for a given path.
This PR unifies it and makes results more predictable.
=> feat: make getLocationForJsonPath more consistent with the YAML equivalent [SO-215]

src/__tests__/getJsonPathForPosition.spec.ts, src/getJsonPathForPosition.ts
YAML's equivalent returns undefined.
=> fix: return undefined when no node is found at given position

src/safeParse.ts
That replace was very expensive in case of huge strings.
Decided to remove other utils - do not really think we need to use them.
=> perf: remove toNumber/toString/isInfinite

src/__tests__/parseWithPointers.ts, src/parseWithPointers.ts
Fixes https://github.com/stoplightio/studio/issues/123
=> fix: include properties with empty string as key

src/__tests__/parseWithPointers.ts, src/parseWithPointers.ts, src/types.ts
Will help with https://github.com/stoplightio/spectral/issues/730
Some extra context can be found in the sibling PR for YAML Package. https://github.com/stoplightio/yaml/pull/32
=> feat: preserveKeyOrder option

src/__tests__/bundle.spec.ts, src/bundle.ts
We use the bundle target in function in our export service if a ref isn't resolved, and it's to a file, an error was being thrown.
Now we no longer throw an error.
=> fix: only bundle local refs

package.json, src/__tests__/bundle.spec.ts, src/bundle.ts, yarn.lock
Before, when bundling $refs to things like response codes (which are numbers) e.g. `200`, it would create an array with 199 undefined elements, and then the object in the 200th spot, rather than an object with a `200` property on it.
Added a test to demonstrate the correct behavior.
=> fix: bundleTarget should maintain array or object from original source

src/__tests__/bundle.spec.ts, src/bundle.ts
We were mutating [objectToBundle](https://github.com/stoplightio/json/blob/dabccdafa5dcb6047d3d1c5ef25703169da9af75/../../Stoplight/json/src/bundle.ts#L21) while also traversing it, which for circular $refs caused an infinite loop 😱 . Not sure if this is the proper way to handle it though.
- fixes https://github.com/stoplightio/platform-internal/issues/3311
- https://stoplight-internal.slack.com/archives/C014Q4UK3NZ/p1593795467000500
=> fix: don't mutate the object being traversed

src/__tests__/bundle.spec.ts, src/bundle.ts
Right now we're throwing an error on the first invalid pointer. In order to provide a better experience to the end user, let's take a similar approach as `json-schema-ref-parser` and continue on error. Then similar to the `__bundled__` object, we can set a `__errors__` and display the invalid $refs to the user.
- Related to https://github.com/stoplightio/platform-internal/issues/3429
=> fix: collect errors while bundling

src/__tests__/bundle.spec.ts, src/bundle.ts
Addresses https://github.com/stoplightio/platform-internal/issues/4548
Re-posting my explanation from Slack:
> It turned out `bundleTarget` in @stoplight/json creates sparse arrays and lodash or some other crap elements (or sth else) uses under the hood does not clone the array correctly.
=>  fix(bundle): ensure lack of sparse arrays in output 

src/__tests__/resolveInlineRef.spec.ts, src/index.ts, src/resolveInlineRef.ts
While working on https://github.com/stoplightio/platform-internal/issues/4548, I realized JSV (as well as platform and elements) do not follow $refs correctly. This is not an issue at the moment due to the nature of bundled format, but may become one at some point.
=> feat: implement resolveInlineRef util

src/__tests__/getLocationForJsonPath.spec.ts, src/getLocationForJsonPath.ts
Needed for https://github.com/stoplightio/platform-internal/issues/5413
=> fix: getLocationForJsonPath should handle incomplete property pair

src/__tests__/resolveInlineRef.spec.ts, src/resolveInlineRef.ts
I reminded myself about this case when working on https://github.com/stoplightio/platform-internal/issues/5879.
Initially, we only took json-schema-ref-parser into the account and forgot we also cope with local $refs, some of which are authored by user and therefore not touched by json-schema-ref-parser at all. The handling of such $refs is essential.
The list of affected areas include `@stoplight/http-spec`, `@stoplight/json-schema-tree`, Studio and possibly platform-internal (export).
It shouldn't be a breaking change for any of the aforementioned projects, but I'm not fully certain in case of the export, so I encourage @stoplightio/platinum-falcons to participate in the review.
=> feat: resolveInlineRef should support summary and description override

src/__tests__/isLocalRef.spec.ts, src/isLocalRef.ts
Sometimes markdown strings can be treated as a valid JSON pointer by the `isLocalRef` method. I decided to go with a very simple regex `^#\S*$` which will make sure that string starts from `#` and does not contain any whitespace characters in it since they're not allowed by https://datatracker.ietf.org/doc/html/rfc6901 in JSON pointers.
=> fix: local refs should not contain any whitespace characters

package.json, src/__tests__/reparentBundleTarget.spec.ts, src/index.ts, src/reparentBundleTarget.ts, yarn.lock
For https://github.com/stoplightio/platform-internal/pull/7479
I'm not sure about the name of it... `reparentBundleTarget` sounds somewhat weird.
=> feat: implement reparentBundleTarget function

src/__tests__/bundle.spec.ts, src/bundle.ts
This is needed to fix performance penalty introduced in `prism-cli` around version 3.2 which uses `bundleTarget` pretty often introducing huge performance overhead on huge documents: https://github.com/stoplightio/prism/issues/1860
=> feat: added option to `bundleTarget` to prevent deep clone of document

src/__tests__/resolveInlineRef.spec.ts, src/resolveInlineRef.ts
Used by https://github.com/stoplightio/http-spec/blob/4afccdcfd88c212b568576b866cf09f8d4aa8e91/src/oas/resolver.ts
This is to be able to tell what the location of the $ref resolved value is to be able to determine the "context" - whether the closest parent is service, path or operation.
=> feat: add resolveInlineRefWithLocation util

.circleci/config.yml
release step in circle ci is failing due to circle ci using old version of node.
=> fix: upgrade node version for release step in circle CI

src/__tests__/bundle.spec.ts, src/bundle.ts
See tests.
Also switches traverse to use `onEnter` rather than `onProperty` to improve performance. This change created quite the diff because it changed the indentation. To see what actually changed (besides using onEnter), check out the first commit -> https://github.com/stoplightio/json/pull/115/commits/532363e159ef9b5c629911b9b8bf07f951fcbc10#diff-93630daa95fd526fa4d642441d8e9baf528afa37551ca9b78a44b480f342c29c.
=> fix(bundleTarget): improve # $ref handling, and preserve circular indirect $refs

src/__tests__/resolveInlineRef.spec.ts, src/extractSourceFromRef.ts, src/index.ts, src/isExternalRef.ts
This fixes an e2e issue in https://github.com/stoplightio/platform-internal/pull/16345 
it's extracted out of a bigger PR #122
=> fix: invalid local pointers containing whitespaces are treated as external by resolveInlineRef

src/decycle.ts
https://smartbear.atlassian.net/browse/STOP-184
Performance Issue for decycle spec
1. Locally run test cases using yarn test
2. Tested this changes in PRISM using yalc
3. Tested this changes in SPECTRAL using yalc
4. Tested this changes in PLATFROM_INTERNAL using yalc
=> Fix/stop 184/performance issue
