stoplightio/json

src/__tests__/getLastPathSegment.spec.ts, src/__tests__/renameObjectKeys.spec.ts, src/__tests__/toPropertyPath.spec.ts, src/getLastPathSegment.ts, src/renameObjectKey.ts, src/toPropertyPath.ts
Related [graphite#108](https://github.com/stoplightio/graphite/pull/108)
=> [SL-1530] renameObjectKey

package.json, src/__tests__/__snapshots__/parseWithPointers.ts.snap, src/__tests__/getJsonPathForPosition.spec.ts, src/__tests__/getLocationForJsonPath.spec.ts, src/__tests__/parseWithPointers.ts, src/getJsonPathForPosition.ts, src/getLocationForJsonPath.ts, src/parseWithPointers.ts, src/types.ts, yarn.lock
~waiting for release ;P~
Released 20mins ago :)
As you can see, it also contains one minor fix - characters are more correct now.
Previously they were shifted by 1, nothing major since we highlight all lines anyway, but still was nice to improve it.
=> feat: switch to npm version of jsonc-parser

package.json, src/encodePointerFragment.ts, src/parseWithPointers.ts, src/pointerToPath.ts, yarn.lock
…so we can deduce types. This is stuck to 5.x
=> chore: package upgrade

src/__tests__/parseWithPointers.ts, src/parseWithPointers.ts, src/types.ts
Needed by https://github.com/stoplightio/spectral/issues/258
=> feat: parserOptions accepts ignoreDuplicateKeys flag

src/__tests__/parseWithPointers.ts, src/parseWithPointers.ts
This is more like a feature, but I want to trigger a patch release. :P
=> fix: include path for DuplicateKey errors

package.json, src/__tests__/renameObjectKeys.spec.ts, src/renameObjectKey.ts, yarn.lock
Causing issues with move operations in graphite.
Also bumped some dev deps, and jsonc parser for a fix included in their latest release.
=> fix: rename object key

src/__tests__/parseWithPointers.ts, src/parseWithPointers.ts
Fixes https://github.com/stoplightio/spectral/issues/751
=> fix: report duplicate keys properly

src/index.ts
oppps, forgot to re-export #40
=> fix: export traverse and bundle modules

src/__tests__/bundle.spec.ts, src/bundle.ts, src/traverse.ts
This is kind of complicated - hopefully the new test demonstrates the problem being solved!
=> fix: scope bundle() to prevent collisions

package.json, yarn.lock
=> chore: update stoplight types

README.md
commit message was in wrong format last time, so change was not released. This will now release a
new version
=> fix(readme update): release stoplight types version bump

src/__tests__/safeStringify.ts, src/safeStringify.ts
This indirectly caused https://stoplight-internal.slack.com/archives/C01019NT0P8/p1596722416373400?thread_ts=1596722262.372400&cid=C01019NT0P8
=> fix: safeStringify may return undefined

src/__tests__/safeStringify.ts, src/safeStringify.ts
This came out of the discussion that took place here https://github.com/stoplightio/json/pull/59
=> fix: improve safeStringify fn signature

src/__tests__/safeStringify.ts, src/safeStringify.ts
This reverts commit d08decfa03e4e5ee295d15703b6cd16c509abfc5. (#60)
=> Revert "fix: improve safeStringify fn signature (#60)"

src/__tests__/bundle.spec.ts, src/bundle.ts
Needed by https://github.com/stoplightio/platform-internal/pull/5102 for https://github.com/stoplightio/platform-internal/issues/4914
=> fix(bundle): create packed array of certain size upfront

src/__tests__/bundle.spec.ts, src/bundle.ts
For https://github.com/stoplightio/platform-internal/pull/5504
Reverts the choice we made here https://github.com/stoplightio/json/pull/74/commits/f26427154c33773e5ef56879dc01043452f3cfb2 and https://github.com/stoplightio/json/pull/74/commits/7b7d309763be22ae72d47ed284414d304769e200#diff-93630daa95fd526fa4d642441d8e9baf528afa37551ca9b78a44b480f342c29cR122
=> fix(bundle-target): nuke existing data under bundleRoot

src/__tests__/bundle.spec.ts, src/bundle.ts
Fixes https://github.com/stoplightio/platform-internal/issues/4732
The test is a mirror of the situation happening in the document in the document provided in the linked ticket.
=> fix(bundle): follow $refs correctly

package.json, src/__tests__/decycle.spec.ts, src/_utils.ts, src/decycle.ts, src/index.ts, src/resolveInlineRef.ts, yarn.lock
- blocking for https://github.com/stoplightio/platform-internal/pull/6180
- find circular javascript references and replace them with a JSON Ref
=> feat: add decycle method

src/__tests__/decodePointer.ts, src/__tests__/pointerToPath.ts, src/decodePointer.ts
For https://github.com/stoplightio/platform-internal/issues/6203
=> fix: decodePointer does not handle percent character

src/__tests__/decycle.spec.ts, src/decycle.ts
- Took me 2 mins to do this, so let's get this into the Schneider circular ref fix!
=> fix: only decylce circular javascript refs

src/__tests__/resolveInlineRef.spec.ts, src/resolveInlineRef.ts
=> fix: resolveInlineRef should handle arrays 

src/__tests__/decycle.spec.ts, src/decycle.ts
Needed by https://github.com/stoplightio/prism/issues/1456
=> fix: handle slashes better when decycling

src/__tests__/traverse.spec.ts, src/traverse.ts
Going to use it in https://github.com/stoplightio/platform-internal/pull/6501
=> feat(traverse): support onEnter/onLeave

.circleci/config.yml, package.json, yarn.lock
[#11028](https://github.com/stoplightio/platform-internal/issues/11028)
upgrade stoplight/types to 13.0.0 to be able to successfully pull in latest version of http-spec into Prism which resolves a critical security issue.
=> fix: upgrade stoplight/types

src/__tests__/bundle.spec.ts, src/bundle.ts
Adds a new `keyProvider` option to the `bundleTarget` function.
This allows the consumer to customize the key values that are used within the `bundleRoot`.
=> feat(bundleTarget): add keyProvider option

src/__tests__/decycle.spec.ts, src/decycle.ts
STOP-184
Modified the code for faster execution.
Tested locally with npm run test.update
=> fix(dereference): modification for circular ref for delete objects

src/decycle.ts
Addresses [ https://smartbear.atlassian.net/browse/STOP-184 ]
Modified the code for faster execution.
Tested locally with npm run test.update
=> fix: Optimised code for performance

src/decycle.ts
#STOP-184
Reverting changes due breaking in prism
Tested locally
=> fix: revert changes of stop-184

package.json, yarn.lock
To upgrade the packages to resolve the vulnerabilities for the following packages in `json` repository  
- minimist 
- acron 
- lodash 
- merge 
- marked 
- npm-user-validate 
- normalize-url 
- kind-of 
- handlebars 
- trim-newlines 
- tar 
- terser 
- serialize-javascript 
- semver-regex 
- http-cache-semantic 
After carefully analyzing, I noticed that above all packages are used internally by our `@stoplight/scripts` package. Currently we are using v7.4.0 version of `@stoplight/scripts`. For the security solution, we need to update the version of `@stoplight/scripts` from v7.4.0 to v9.3.4. 
Reference document - https://smartbear.atlassian.net/wiki/spaces/Stoplight/pages/4454809713/Security+ticket+document
=> chore(deps): bump @stoplight-scripts from v7.0.4 to v9.3.4

.circleci/config.yml, package.json, yarn.lock
[STOP-1105](https://smartbear.atlassian.net/jira/software/c/projects/STOP/boards/2033?assignee=712020%3Ae7af16c3-6282-4504-8e21-2ee8d0ac31f2&selectedIssue=STOP-1105)
I have upgraded the rollup version from 2.79.1 to 4.22.2 to resolve this issue.
This is devdependency used to to build and test. I have tested the changes by executing the build, test, test.prod, test.update, lint, lint.fix commands. All the mentioned command executed successfully.
[STOP-1105]: https://smartbear.atlassian.net/browse/STOP-1105?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore(deps): bump rollup from 2.47.0 to 4.22.4

package.json, yarn.lock
[STOP-907](https://smartbear.atlassian.net/browse/STOP-907)
I have upgraded the rollup version from 3.0.0 to 4.2.1 to resolve this issue.
This is devdependency used to to build and test. I have tested the changes by executing the build, test, test.prod, test.update, lint, lint.fix commands. All the mentioned command executed successfully.
[STOP-907]: https://smartbear.atlassian.net/browse/STOP-907?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore(deps): dot-prop bump from 3.0.0 to 4.2.1

package.json, yarn.lock
[STOP-906](https://smartbear.atlassian.net/browse/STOP-906)
braces bump from 3.0.2 to 3.0.3
Tested locally by executing the build, test, test.prod, test.update, lint, lint.fix commands. All commands executed successfully.
[STOP-906]: https://smartbear.atlassian.net/browse/STOP-906?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore(deps): braces bump from 3.0.2 to 3.0.3

package.json, yarn.lock
[STOP-942](https://smartbear.atlassian.net/browse/STOP-942)
To resolve the security issue, I have upgraded ini version from 1.3.5 to 1.3.6
Tested locally by executing the build, test, test.prod, test.update, lint, lint.fix commands. All commands executed successfully. Also done testing with platform-internal repo using yalc.
[STOP-942]: https://smartbear.atlassian.net/browse/STOP-942?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore(deps): ini bump from 1.3.5 to 1.3.6
